return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  build = ':TSUpdate',
  lazy = false,
  opts = {
    ensure_installed = {
      'bash',
      'css',
      'diff',
      'elixir',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'gotmpl',
      'gowork',
      'heex',
      'html',
      'hurl',
      'javascript',
      'json',
      'lua',
      'markdown',
      'nix',
      'python',
      'rust',
      'sql',
      'templ',
      'toml',
      'typescript',
      'typst',
      'vim',
      'vimdoc',
      'vue',
      'yaml',
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
