return {
  'romus204/tree-sitter-manager.nvim',
  dependencies = {}, -- tree-sitter CLI must be installed system-wide
  config = function()
    require('tree-sitter-manager').setup({
      ensure_installed = {
        'bash',
        'css',
        'diff',
        'elixir',
        'dockerfile',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'gosum',
        'gotmpl',
        'gowork',
        'heex',
        'html',
        'hurl',
        'javascript',
        'json',
        'lua',
        'markdown',
        'nix',
        'python',
        'rust',
        'sql',
        'templ',
        'toml',
        'typescript',
        'typst',
        'vim',
        'vimdoc',
        'vue',
        'yaml',
      },
      nerdfont = false,
    })
  end,
}
