require('config.package_manager')
require('config.settings')
require('config.lsp')
require('config.completion')
require('config.treesitter')
require('config.telescope')
require('config.indent_blankline')
require('config.mappings')
