- name: Dotfiles
  hosts: localhost
  connection: local

  vars:
    home: "{{ ansible_facts['user_dir'] }}"
    xdg_config_home: "{{ home }}/.config"

    # Node.js packages
    node_packages:
      - name: typescript
        version: 5.9.3
      - name: typescript-language-server
        version: 5.1.0
      - name: "@vue/language-server"
        version: 3.1.3
      - name: "@vue/typescript-plugin"
        version: 3.1.3

    # Fonts
    fonts:
      - url: https://github.com/be5invis/Iosevka/releases/download/v34.1.0/PkgTTC-Iosevka-34.1.0.zip
        files:
          - Iosevka-Bold.ttc
          - Iosevka-ExtraBold.ttc
          - Iosevka-ExtraLight.ttc
          - Iosevka-Heavy.ttc
          - Iosevka-Light.ttc
          - Iosevka-Medium.ttc
          - Iosevka-Regular.ttc
          - Iosevka-SemiBold.ttc
          - Iosevka-Thin.ttc
      - url: https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip
        files:
          - Inter.ttc

  tasks:
  - name: Configs
    ansible.builtin.import_tasks:
      file: configs/main.yaml
    tags:
      - configs

  - name: Node.js packages
    ansible.builtin.import_tasks:
      file: node_packages/main.yaml
    tags:
      - node_packages

  - name: Import Fonts tasks
    ansible.builtin.import_tasks:
      file: fonts/main.yaml
    tags:
      - fonts
