- name: Fish Shell
  block:
    - name: Fish - Create directories
      ansible.builtin.file:
        path: "{{ fish_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/fish/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: Fish - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ fish_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/fish/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - fish

- name: Neovim
  block:
    - name: Neovim - Create directories
      ansible.builtin.file:
        path: "{{ nvim_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/nvim/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: Neovim - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ nvim_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/nvim/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - nvim

- name: GnuPG
  block:
    - name: GnuPG - Create directories
      ansible.builtin.file:
        path: "{{ gnupg_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/gnupg/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: GnuPG - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ gnupg_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/gnupg/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - gnupg

- name: Git
  block:
    - name: Git - Create directories
      ansible.builtin.file:
        path: "{{ git_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/git/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: Git - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ git_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/git/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - git

- name: bat
  block:
    - name: bat - Create directories
      ansible.builtin.file:
        path: "{{ bat_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/bat/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: bat - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ bat_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/bat/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - bat

- name: Ghostty
  block:
    - name: Ghostty - Create directories
      ansible.builtin.file:
        path: "{{ ghostty_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/ghostty/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: Ghostty - Write configs
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ghostty_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/ghostty/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - ghostty

- name: OpenCode
  block:
    - name: OpenCode - Create directories
      ansible.builtin.file:
        path: "{{ opencode_config_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ lookup('community.general.filetree', 'configs/files/opencode/', wantlist=True) | selectattr('state', '==', 'directory') }}"

    - name: OpenCode - Write configs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ opencode_config_dir }}/{{ item.path }}"
      loop: "{{ lookup('community.general.filetree', 'configs/files/opencode/', wantlist=True) | selectattr('state', '==', 'file') }}"
  tags:
    - opencode
